### ISSUE TITLE
Schema.org dev API

### ISSUE THREAD

**Issue by wpsumo** [Yoast/developer#147]
## Is your feature request related to a problem? Please describe.

I feel the dev API documentaiton is a bit thin and don't bring enough informaiton and example how to use it therefore I ask here. It would be good with several of examples how to do this and that. But right now it's not even showing all hooks.

## Describe the solution you'd like
I have two things I would like to do:
- Extend the Organization to include more data. 
- Enable and allow author JSON-LD on pages.

How do I define if I want fields to be inserted after a specific field in my case e.g I would like to insert these in specific places. legalName after name and foundingDate after logo.
```
  $data['legalName'] = 'Example Yoast ltd';
  $data['foundingDate'] = '2009';
```

I just found ways of inserting it efter the last default field in the `@type`. Is it possible to insert specific entries after specific points to keep a better structure? Couldn't find anything in the documenation?

See example code here:

```
/**
 * Add extra data to schema Organization
 *
 * @api array $data The graph piece to filter.
 *
 * @return array
 */
add_filter( 'yoast_seo_development_mode', '__return_true' );
function custom_wpseo_schema_organization($data){
  
  $data['address'] = [
    '@type' => 'PostalAddress',
    'streetAddress' => 'My address',
    'postalCode' => 'My postal code',
    'addressLocality' => 'City',
    'telephone' => '0123456789',
  ];
  $data['@type'] = 'Organization';
  $data['legalName'] = 'Example Yoast ltd';
  $data['foundingDate'] = '2009';	
  $data['telephone'] = '0123456789';
  $data['image'] = 'pathtoimage';
  $data['priceRange'] = '$$';

  return $data;
}
add_filter('wpseo_schema_organization', 'custom_wpseo_schema_organization', 10, 1);
```

My second question is how I can enable author output in the schema for articles to allow to fetch author information? As you today restrict it to only allow on post and not pages. How can I allow it on pages?

**Comment by jonoalderson** [comment]
Sorry for the slow response to your question; it looks like it got lost in our backlog!

There are a few questions here, so apologies if I miss or confuse anything. So, in order:

- We don't provide a way to add properties in a specific place/order (this doesn't have any impact other than cosmetics), but this is something you could solve yourself with some rudimentary PHP. E.g., you could use `ksort()` on the `$data` array before returning it.

- You could add author output on pages by:
  - Filtering the `WebPage` (similarly to your `organization` filter) to add the `author` property
  - Following our example [here](https://developer.yoast.com/features/schema/integration-guidelines/#an-example-use-case) to add a new custom piece (in which you'd construct + describe the user, using your own logic).

- If you're querying things that there might be multiple instances of, then you'll need to check their properties and find out which one you're changing. You could check against the ID, for example. If you're wanting to _add_ multiple instances of an object, these will also need unique IDs, and can just be added as members of an array on their respective parent node.

I'm going to close this issue as we're unlikely to add specific support to the API for these scenarios; however, we'll continue to improve the API documentation with diverse and practical examples!

Feel free to continue to reply if you have any more questions, and I'll try to help as best I can.

**Comment by wpsumo** [comment]
@jonoalderson Thanks for the answer.

> We don't provide a way to add properties in a specific place/order (this doesn't have any impact other than cosmetics), but this is something you could solve yourself with some rudimentary PHP. E.g., you could use ksort() on the $data array before returning it.


Thanks, my question was more to when I extend for example the author data I want to inject it in a specific location that make sense. Is there a way to decide exactly where to inject it? I can just extend the schema at the bottom, either if I create a new parent or add children to an existing parent node. Am I missing something, or is there no way to extend from the part I want? It is also a bit as you say cosmetics, but still find the code easier to read than when its randomly inserted. I want to insert it after x parent or y children.

**Comment by jonoalderson** [comment]
You'd need to use PHP to manipulate the `$data` array. You can apply any logic you like on that to sort/order/arrange.

**Comment by wpsumo** [comment]
@jonoalderson Sure but a helper would be useful to not redo the whole piece or to filter and slice an array. Feels overdoing it?

Like this is your suggestions right?

```
$data = array(
  'zero'  => '0',
  'one'   => '1',
  'two'   => '2',
  'three' => '3',
);
$res = array_slice($array, 0, 3, true) +
    array("my_key" => "my_value") +
    array_slice($data, 3, count($data) - 1, true) ;
print_r($res);
```


Wouldn like` $data->['url'] = esc_url( $url )`; make live so much easier making a helper for this?

**Comment by jonoalderson** [comment]
I'm not sure I understand what you're trying to achieve, sorry.
If you're just wanting to insert a property, then you can use `$data['url'] = esc_url( $url );`. If you're trying to insert it at a specific point in the array, you'll need to write some PHP based on your requirements.
I'm not sure that a helper would be helpful here, as you'd still need to define exactly what you want to do - which would require (almost) the same PHP.
