### ISSUE TITLE
Update section on monorepo linking

### ISSUE THREAD

**Issue by mhkuu** [Yoast/developer#148]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/developer-docs/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of the issue

I've been told the command `yarn link-monorepo` is not available nor necessary anymore, as described in [this section of the development setup](https://developer.yoast.com/development/environment/setup#linking-repositories-via-yarn). Could you please update this section?

**Comment by jdevalk** [comment]
Do you know what it should be? If so please feel free to update the documentation straight away.

**Comment by jdevalk** [comment]
Ok, fixed then in [9753bdb](https://github.com/Yoast/developer/commit/9753bdbaf7e59733a8c5b2c4b4ffca64d7db6cbb)
