### ISSUE TITLE
Pagination and dupe meta descriptions

### ISSUE THREAD

**Issue by alexmoss** [Yoast/developer#247]
### Please give us a description of the issue
Paginated URLs are using the same meta description, causing duplication issues. All listed URLs affected can be found [here](https://docs.google.com/spreadsheets/d/1p-efOrkegbK4wEE6KM7airhEmzCdsay5/edit#gid=1247521701).

Not only does this include pagination, but also other pages that will have been duplicated and the meta description overlooked (rows 31-40 inclusive in the link above) and should be made unique.

Rows 41 onwards do not apply to this issue.

**Comment by petaryoast** [comment]
@alexmoss if MD is for an "archive" page (please see changelogs), how would we go about making MD unique for each page? (eg Page 1, page 2 etc)

**Comment by alexmoss** [comment]
Yes exactly - eg "Yoast developer blog archive for [archive name], page [page number]"

**Comment by petaryoast** [comment]
Very nice. Thanks!
