### ISSUE TITLE
Add lastmod to XML sitemap

### ISSUE THREAD

**Issue by jdevalk** [Yoast/developer#285]
### Please give us a description of the issue
The XML sitemap for `developer.` doesn't have a `lastmod` value because Docusaurus doesn't support that. I came across [this solution](https://johnnyreilly.com/adding-lastmod-to-sitemap-git-commit-date) for adding `lastmod` that I thought was smart, I'd suggest implementing it.

* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/developer/blob/main/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by mhkuu** [comment]
Thanks a lot for the suggestion! 🙌 Implemented through #331.
