### ISSUE TITLE
Hybrid types & composite IDs in Developer Documentation

### ISSUE THREAD

**Issue by alexmoss** [Yoast/developer#289]
### Please give us a description of the issue
Within [this area](https://developer.yoast.com/features/schema/technology-approach/#hybrid-types--composite-ids), there is a missing bullet point after "**; and**":

![image](https://github.com/Yoast/developer/assets/1687659/09a9357b-1b9c-4a2c-94a5-db7e035fcb28)

Please can this be updated with the relevant information? Thanks

**Comment by enricobattocchi** [comment]
We should probably just remove the "; and" since the intended bullet point is not relevant anymore, and was removed when dev docs [were moved to the current setup](https://github.com/Yoast/developer/pull/145):
```
* The `{{identifier}}`value should concatenate the `{{identifier}}` values from each member, in alphabetical order by `@type` (e.g., `1-abc123` for an `organization` with ID `1` and a `person` with ID `abc123`).
```
