### ISSUE TITLE
Typo on Integrations Guidelines Page for Schema `@type` Property

### ISSUE THREAD

**Issue by rpovelones** [Yoast/developer#305]
### Please give us a description of the issue
There is a small typo on the [Integrations Guidelines Page](https://github.com/Yoast/developer/blob/main/docs/features/schema/integration-guidelines.md?plain=1#L81) on line 81 where `type` should be updated to `@type`. This typo will prevent the new schema from being added to the graph and will silently fail.

* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/developer/blob/main/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by mhkuu** [comment]
Thanks for the report @rpovelones! 👍 Fixed through #306.
