### ISSUE TITLE
Change webpage type schema API needs an extra check

### ISSUE THREAD

**Issue by shabnam611** [Yoast/developer#333]
### Please give us a description of the issue
If we exactly copy the following example from the [webpage type schema](https://developer.yoast.com/features/schema/pieces/webpage/#api), it doesn't change the type into About page, 

```
add_filter( 'wpseo_schema_webpage', 'example_change_webpage' );

/**
 * Changes @type of Webpage Schema data.
 *
 * @param array $data Schema.org Webpage data array.
 *
 * @return array Schema.org Webpage data array.
 */
function example_change_webpage( $data ) {
    if ( ! is_page( 'about' ) ) {
        return $data;
    }

    $data['@type'] = 'AboutPage';

    return $data;
}
```

however, adding an extra check makes the filter work correctly.

```
add_filter( 'wpseo_schema_webpage', 'example_change_webpage' );

/**
 * Changes @type of Webpage Schema data.
 *
 * @param array $data Schema.org Webpage data array.
 *
 * @return array Schema.org Webpage data array.
 */
function example_change_webpage( $data ) {
    if ( ! is_page( 'about' ) && $data['@type'] != 'AboutPage') {
        $data['@type'] = 'AboutPage';
    }

    /*$data['@type'] = 'AboutPage';*/

    return $data;
}
```

* [ ] I've read and understood the [contribution guidelines](https://github.com/Yoast/developer/blob/main/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by enricobattocchi** [comment]
@shabnam611 I'm afraid that the new code would make every page `AboutPage`
maybe the problem was happening because the page you were trying to edit was not called `about`?

**Comment by shabnam611** [comment]
Hi @enricobattocchi 
Thank you. I used wrong slug.
